In [2]:
import numpy as np
import random

#### 배열(Array)
python의 list와 비슷하나 더 높은 dimention의 데이터를 다룰 수 있음

##### Array 생성하기

In [3]:
list1 = []
array1 = np.array([])
print(list1)
print(array1)
print('type of list1 : ',type(list1))
print('type of array1 : ',type(array1))

[]
[]
type of list1 :  <class 'list'>
type of array1 :  <class 'numpy.ndarray'>


##### 크기를 확인하고 싶을 때

In [4]:
list2 = [random.randint(0,10) for x in range(5)]
array2 = np.random.randint(low=0, high=10, size=5)

print(list2)
print(array2)

print('================================')
print('list2의 길이 :', len(list2))
print('array2의 모양 :', array2.shape)
print('array2의 크기 :', array2.size)
print('array2의 길이 :', len(array2))  # 리스트 오브젝트에는 shape, size attribute가 없지만 array에는 len을 쓸 수는 있음. 
print('=====================================')
print('비어있는 array의 모양 :', array1.shape)

[0, 5, 3, 3, 1]
[2 8 1 7 9]
list2의 길이 : 5
array2의 모양 : (5,)
array2의 크기 : 5
array2의 길이 : 5
비어있는 array의 모양 : (0,)


In [26]:
array3 = np.random.randint(0,10,(4,3))
print(array3)
print('================================')
print('array3의 모양 :', array3.shape)
print('array3의 크기 :', array3.size)
print('array3의 행길이:', array3.shape[0])
print('array3의 행길이:', len(array3))
print('array3의 차원:', array3.ndim)

[[2 2 5]
 [3 2 5]
 [8 2 1]
 [2 0 2]]
array3의 모양 : (4, 3)
array3의 크기 : 12
array3의 행길이: 4
array3의 행길이: 4
array3의 차원: 2


###### 참고) array의 ndim은 array shape의 길이, 즉, len(array.shape)과 같음

##### list를 array로

In [6]:
list3 = array3.tolist()
print('2차원 array를 list로 바꾸면:', list3)
list2_2 = array2.tolist()
print('1차원 array를 list로 바꾸면:', list2)

2차원 array를 list로 바꾸면: [[0, 7, 6], [5, 1, 9], [9, 0, 2], [6, 6, 9]]
1차원 array를 list로 바꾸면: [0, 5, 3, 3, 1]


##### array 원하는 배열 추출하기
###### slicing & indexing 

In [7]:
# 열 추출 
row3 = array3[3]
row3_1 = array3[3,:]
print(row3)
print('row3의 모양:', row3.shape)
print('row3_1의 모양:', row3_1.shape)
print('====================')
print(len)
# 행 추출
col2 = array3[:,2]
print(col2)
print('col2의 모양:', col2.shape)
## 열방향으로 추출하든, 행방향으로 추출하든 결과물의 모양은 같다.

[6 6 9]
row3의 모양: (3,)
row3_1의 모양: (3,)
<built-in function len>
[6 9 2 9]
col2의 모양: (4,)


좀더 고급진 방법이 있다

In [42]:
# Boolean indexing
array4 = np.random.randint(0,10,(4,3))
print(array4)
print('---------------')
bool_array4 = array4 > 3
print(bool_array4)
print('---------------')
print(array4[bool_array4])

[[4 0 9]
 [5 2 5]
 [4 3 6]
 [0 8 7]]
---------------
[[ True False  True]
 [ True False  True]
 [ True False  True]
 [False  True  True]]
---------------
[4 9 5 5 4 6 8 7]


In [49]:
# fancy indexing
array5 = np.random.randint(0,10,(6,5))
print(array5)
print('---------------')
idx = [0,2,4]
print(array5[idx])
print('---------------')
print(array5[:, idx])

[[6 5 5 3 0]
 [3 7 2 0 4]
 [8 0 0 5 5]
 [1 4 5 3 4]
 [6 9 0 8 4]
 [2 1 8 5 0]]
---------------
[[6 5 5 3 0]
 [8 0 0 5 5]
 [6 9 0 8 4]]
---------------
[[6 5 0]
 [3 2 4]
 [8 0 5]
 [1 5 4]
 [6 0 4]
 [2 8 0]]


#### array 연결하기
##### concatenate / stack / vstack / hstack
###### 위에서 생성한 row3이나 col2 처럼 (k, ) 모양의 array를 차곡차곡 쌓고 싶다면..

In [8]:
building1 = np.array([])
building2 = np.array([])


for i in range(0, 5):
    block = np.random.randn(8,)   ### 여러가지 random 모듈에 관한 설명은 다음 블록에서 확인
    building1 = np.concatenate((building1, block))
    building2 = np.hstack((building2, block))

print('concatenate 사용:', building1.shape)
print('hstack 사용:', building2.shape)

concatenate 사용: (40,)
hstack 사용: (40,)


In [9]:
building3 = np.array([])   # shape : (0,)
building4 = np.array([])

for i in range(0, 5):
    block = np.random.randn(8,)  
    building3 = np.vstack((building3, block))     
    building4 = np.stack((building4, block))

print('vstack 사용:', building3.shape)
print('stack 사용:', building4.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 8

##### np.reshape을 사용해보자

In [10]:
building3 = np.reshape(np.array([]), (8,))  
building4 = np.reshape(np.array([]), (8,))

ValueError: cannot reshape array of size 0 into shape (8,)

##### 안됨...
##### zeros 를 사용하는 수밖에 없다.

In [11]:
building3 = np.zeros((8,))  # shape : (8,0)
building4 = np.zeros((8,))

for i in range(0, 5):
    block = np.random.randn(8,)  
    building3 = np.vstack((building3, block))     
    #building4 = np.stack((building4, block))

print('vstack 사용:', building3.shape)
#print('stack 사용:', building4.shape)

vstack 사용: (6, 8)


##### 대신 맨 위 열이 빈 array가 아니라 모든 값이 0인 array를 넣은 것이라서 행의 갯수가 5가 아니라 6임
##### 나중에 데이터 분석할 때 거슬리면 np.delete(building3, 0, axis = 0)으로 지우면 됨
##### np.stack을 주석처리한 이유는?? => 돌리면 이건 여전히 오류남 ValueError: all input arrays must have the same shape
##### 아래와 같이 한번만 쌓는게 가능하다...

In [12]:
building4 = np.zeros((8,))
building5 = np.zeros((8,))

for i in range(0, 1):  ###########
    block = np.random.randn(8,)   
    building4 = np.stack((building4, block))
    building5 = np.stack((building5, block), axis = 1)

print('stack 사용:', building4.shape)
print('axis=1로 했을 때:', building5.shape)  ##### default는 axis = 0

stack 사용: (2, 8)
axis=1로 했을 때: (8, 2)


##### (k, )는 그렇고, 모양이 (n,m)인 array를 연결하는 건 어떻게?

In [13]:
building6 = np.empty(shape=[0,3])  # <- 여기가 중요!! 차원의 갯수를 맞춰줘야함.
building7 = np.empty(shape=[0,3])

for i in range(0, 3):  
    block = np.random.randint(0,5,(4,3))   
    building6 = np.concatenate((building6, block))
    building7 = np.vstack((building7, block))

print('concatenate 사용:', building6.shape)
print('vstack 사용:', building7.shape)

concatenate 사용: (12, 3)
vstack 사용: (12, 3)


In [14]:
building8 = np.empty(shape=[4,0])  # <- 여기가 중요!! 차원의 갯수를 맞춰줘야함.
building9 = np.empty(shape=[4,0]) 
for i in range(0, 3):  
    block = np.random.randint(0,5,(4,3))   
    building8 = np.concatenate((building8, block), axis=1)
    building9 = np.hstack((building9, block))

print('concatenate 사용:', building8.shape)
print('hstack 사용:', building9.shape)


concatenate 사용: (4, 9)
hstack 사용: (4, 9)


###### 그럼 도대체 stack은 왜 따로 있는 걸까..?
#### stack의 진정한 사용처!!

In [23]:
building10 = np.empty(shape=[4,3])   
building11 = np.empty(shape=[4,3]) 
for i in range(0, 1):  
    block = np.random.randint(0,5,(4,3))   
    building10 = np.stack((building10, block), axis=0)
    building11 = np.stack((building11, block), axis=1)
print('stack 사용:', building10.shape)
print('stack(axis=1) 사용:', building11.shape)
print('=====================================')
building10_1 = np.empty(shape=[2, 4, 3]) 

building10_2 = np.stack((building10, building10_1))
building10_3 = np.stack((building10, building10_1), axis=1)
building10_4 = np.stack((building10, building10_1), axis=2)
building10_5 = np.stack((building10, building10_1), axis=3)

print('axis = 0:', building10_2.shape)
print('axis = 1:', building10_3.shape)
print('axis = 2:', building10_4.shape)
print('axis = 3:', building10_5.shape)


stack 사용: (2, 4, 3)
stack(axis=1) 사용: (4, 2, 3)
axis = 0: (2, 2, 4, 3)
axis = 1: (2, 2, 4, 3)
axis = 2: (2, 4, 2, 3)
axis = 3: (2, 4, 3, 2)


## np.random module
### randint() / rand() / randn()

In [35]:
print('<np.random.randint()>')
print(np.random.randint(5))           # 0-4 사이의 랜덤 정수 한개 뽑아 줌
print('----------------------------------')
print(np.random.randint(1,10,(4,3)))  # 1-9 사이의 랜덤 정수를 뽑아 shape (4,3) 인 array 생성
print('----------------------------------')
print('<np.random.rand()>')
print(np.random.rand(5))              # 0-1 사이의 실수를 5개 뽑아서 array 생성
print('----------------------------------')
print(np.random.rand(4,3))
print('----------------------------------')
print('<np.random.randn()>')
print(np.random.randn(5))             # 표준정규분포(N(0,1))에서 5개 숫자를 뽑아서 array 생성
print('----------------------------------')
print(np.random.randn(4,3))


<np.random.randint()>
3
----------------------------------
[[2 8 4]
 [1 3 1]
 [6 5 4]
 [8 9 4]]
----------------------------------
<np.random.rand()>
[0.83587785 0.33415253 0.89594629 0.78869216 0.38098101]
----------------------------------
[[0.22662999 0.87344141 0.42091175]
 [0.32613355 0.89645217 0.40173652]
 [0.6497207  0.07211041 0.38301687]
 [0.33261723 0.81577267 0.87909607]]
----------------------------------
<np.random.randn()>
[ 0.10528475  1.28165277  0.1233065  -0.60488352  0.20410853]
----------------------------------
[[-0.42794828  0.86784517 -0.1629436 ]
 [-0.59451772  0.43574318  1.69058701]
 [ 0.39038417 -0.09192018  1.10723121]
 [ 0.09416711  0.88144623 -1.24009184]]


그 외 알아두면 유용한 함수들

1. np.arange() : list의 range()와 유사한 함수
2. np.linspace()

In [51]:
array6 = np.arange(1, 10) 
array6.reshape(3,-1) # 대신 array6의 길이가 3으로 안나눠떨어지면 오류남


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
print(np.arange(1, 8, 2))  # start, stop, step
print(np.arange(1, 9, 2))  # 단, (stop 숫자 - 1) 까지만 나타냄

[1 3 5 7]
[1 3 5 7]


In [62]:
np.linspace(1, 17, 3)  # start, stop, count

array([ 1.,  9., 17.])

sum, mean, min, max : axis 선정이 중요함

In [84]:
array7 = np.random.randint(1,10,(4,5))
print(array7)
print('------------------------------')
print('array.sum() : 모든 수 다 더한 것')
print(array7.sum())
print('------------------------------')
print('sum(array) : 행 값을 다 더한 것')
print(sum(array7))
print('------------------------------')
print('array.sum(axis=1) : 열 값을 다 더한 것')
print(array7.sum(axis=1))   # sum(array7, axis=1) 이렇게는 못씀
print('------------------------------')
print('array.mean() : 모든 값의 평균')
print(array7.mean())
print('------------------------------')
print('array.mean(axis=0) : 각 열의 평균을 얻을 수 있음')
print(array7.mean(axis=0))
print(sum(array7)/array7.shape[0])
print('------------------------------')
print('array.mean(axis=1) : 각 행의 평균을 얻을 수 있음')
print(array7.mean(axis=1))
print(array7.sum(axis=1)/array7.shape[1])



[[6 3 6 6 7]
 [3 1 9 3 8]
 [9 1 7 5 5]
 [4 4 5 8 3]]
------------------------------
array.sum() : 모든 수 다 더한 것
103
------------------------------
sum(array) : 행 값을 다 더한 것
[22  9 27 22 23]
------------------------------
array.sum(axis=1) : 열 값을 다 더한 것
[28 24 27 24]
------------------------------
array.mean() : 모든 값의 평균
5.15
------------------------------
array.mean(axis=0) : 각 열의 평균을 얻을 수 있음
[5.5  2.25 6.75 5.5  5.75]
[5.5  2.25 6.75 5.5  5.75]
------------------------------
array.mean(axis=1) : 각 행의 평균을 얻을 수 있음
[5.6 4.8 5.4 4.8]
[5.6 4.8 5.4 4.8]


np.where() : 조건, 참인 경우 넣어줄 것, 거짓일 경우 넣어줄 것


In [87]:
truearr = np.array([1,2,3,4,5])
falsearr = np.array([-1, -2, -3, -4, -5])
condition = np.array([True, False, True, False, True])
np.where(condition, truearr, falsearr)

array([ 1, -2,  3, -4,  5])

In [91]:
array8 = np.random.randn(4, 4)
print(array8)
np.where(array8 >= 0, '양수', '음수')

[[-0.78771476  0.38051749 -1.92372397 -0.68818648]
 [ 1.34717698 -0.8975977   0.21503322 -0.60139842]
 [ 1.32290883  0.14650228  0.45985075 -1.35979481]
 [-1.27317116  1.63183147 -0.08278731 -0.07674923]]


array([['음수', '양수', '음수', '음수'],
       ['양수', '음수', '양수', '음수'],
       ['양수', '양수', '양수', '음수'],
       ['음수', '양수', '음수', '음수']], dtype='<U2')

배열 참조 방지하기 : copy()

In [100]:
array9 = np.random.randint(1,10, (4,5))
print('array9:',array9)
array9_1 = array9[:,4]
print('array9_1:',array9_1)

array9_1[0] = 1234
print('--------------------------')
print('array9_1:',array9_1)
print('array9:',array9)

array9: [[9 3 4 7 1]
 [5 2 8 4 7]
 [9 8 4 1 8]
 [9 7 5 5 8]]
array9_1: [1 7 8 8]
--------------------------
array9_1: [1234    7    8    8]
array9: [[   9    3    4    7 1234]
 [   5    2    8    4    7]
 [   9    8    4    1    8]
 [   9    7    5    5    8]]


In [102]:
array9_1 = array9[:,4].copy()
print('array9_1:',array9_1)

array9_1[3] = 4321
print('--------------------------')
print('array9_1:',array9_1)
print('array9:',array9)

array9_1: [1234    7    8    8]
--------------------------
array9_1: [1234    7    8 4321]
array9: [[   9    3    4    7 1234]
 [   5    2    8    4    7]
 [   9    8    4    1    8]
 [   9    7    5    5    8]]


파일 저장 또는 불러오기 : save / load

In [ ]:
np.save('my_arr', array1)  # .npy라는 파일로 저장됨
# 다중 배열 저장하기
np.savez('my_arrz', key1=array2, key2=array3)
loaded_arr = np.load('my_arrz.npy')
loaded_arr.files # [key1, key2] 저장된 key값을 조회할 수 있음